### PR TITLE
Support for Colab & tpu

### PR DESCRIPTION
**Pull request by HighCWu**
Change keras to tf.keras for tpu using.
Rename directory 'google' to 'google_bert' for namespace conflict reason while using Colab.
I create a colab ipynb file based on your 'tutorial.ipynb' for tpu support. 
Some variables are uninitialized after 'keras_to_tpu_model', so I initialized them. I don't know if it's right. 
If yes, you can try to add my colab code to this repo.
Here is the colab code:
https://colab.research.google.com/gist/HighCWu/3a02dc497593f8bbe4785e63be99c0c3/bert-keras-tutorial.ipynb

### CODE REVIEW

**Comment by HighCWu** [comment]
In my mind, it seems tf.keras doesn't have the theano backend. I don't know the resolution at present.

**Comment by Separius** [comment]
Wow, thanks man, I checked your code and it seems legit; thanks for your contribution!

**Comment by HighCWu** [comment]
@Separius  if it's OK, I think you can add a link to the Colab tutorial code in the README and other programmers can get the right way to use free TPU.

**Comment by Separius** [comment]
sure, I will add the link in a moment

**Pull request merged**
